global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'nestjs'
    static_configs:
      - targets: ['nestjs:3211']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'monitoring-web'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'apache-exporter'
    static_configs:
      - targets: ['apache-exporter:9117']

