global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node-exporter.yml

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'nestjs'
    static_configs:
      - targets: ['nestjs:3211']

  - job_name: 'mongo'
    static_configs:
      - targets: ['mongo:27017']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'monitoring-web'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/cadvisor.yml

  - job_name: 'nginx-exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/nginx-exporter.yml

  - job_name: 'apache-exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/apache-exporter.yml

